### ISSUE TITLE
GTU does not compile

### ISSUE THREAD

**Issue by v00d00m4n** [Matsilagi/reshade-retroarch-shaders#1]
Got this error
2017-11-04T20:54:15:495 [33632] | ERROR | Failed to compile 'J:\Program Files (x86)\Steam\steamapps\common\Mystik_Belle\CRT\GTU.fx':
J:\Program Files (x86)\Steam\steamapps\common\Mystik_Belle\Shader@0x10417960(53,6-98): warning X3553: can't use gradient instructions in loops with break, forcing loop to unroll
J:\Program Files (x86)\Steam\steamapps\common\Mystik_Belle\Shader@0x10417960(50,1-51): error X3511: unable to unroll loop, loop does not appear to terminate in a timely manner (249 iterations) or unrolled loop is too large, use the [unroll(n)] attribute to force an exact higher number
J:\Program Files (x86)\Steam\steamapps\common\Mystik_Belle\CRT\GTU.fx(163, 8): error: internal shader compilation failed
J:\Program Files (x86)\Steam\steamapps\common\Mystik_Belle\Shader@0x1809F040(63,16-138): warning X3553: can't use gradient instructions in loops with break, forcing loop to unroll
J:\Program Files (x86)\Steam\steamapps\common\Mystik_Belle\Shader@0x1809F040(61,1-51): error X3511: unable to unroll loop, loop does not appear to terminate in a timely manner (599 iterations) or unrolled loop is too large, use the [unroll(n)] attribute to force an exact higher number
J:\Program Files (x86)\Steam\steamapps\common\Mystik_Belle\CRT\GTU.fx(197, 8): error: internal shader compilation failed

**Comment by luluco250** [comment]
Fixed and made a pull request: https://github.com/Matsilagi/reshade-retroarch-shaders/pull/2
